### ISSUE TITLE
Multiple instances on same page - all scroll together

### ISSUE THREAD

**Issue by corydavidwilliam** [itemslide/itemslide.github.io#38]
What is the best way to implement multiple instances of itemslide on the same page?  Currently all instances scroll together, they need to scroll individually.

My current initialization:

```javascript
var carousel;
carousel = jQuery(".post-image-container ul");
carousel.itemslide();
```

**Comment by nir9** [comment]
Hi,
I added a new two carousels on one page example and each scroll individually so you can check it out: http://itemslide.github.io/examples/two_carousels/

I think the reason it scrolls together in your initialization is because you init all carousel with one init, you need to initialize every carousel separately and give each a unique name (see the source code of the two carousels example)
